---
# tasks file for universal-tomcat

- name: Insure Required Packages Are Installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - tar
    - wget

# Here We Create The Group and User
- name: Create Tomcat Group
  group:
    name: "{{ tomcat_user_group }}"
    state: present

- name: Create Tomcat user
  user:
    name: "{{ tomcat_user_name }}"
    home: "{{ tomcat_user_home }}"
    group: "{{ tomcat_user_group }}"
    system: "{{ tomcat_user_system }}"
    createhome: true
    comment: "Tomcat Service User"

- name: Check If Already Installed
  stat:
    path: "{{ tomcat_base_dir }}/apache-tomcat-{{ tomcat_version }}"
  register: __tomcat_exists

# Creating Basic Locations
- name: Create Temporary Storage Location
  when: not __tomcat_exists.stat.exists
  file:
    state: directory
    path: "{{ tomcat_tmp_storage }}"

- name: Download Tomcat
  when: not __tomcat_exists.stat.exists
  ignore_errors: True
  with_items: "{{ tomcat_mirrors }}"
  get_url:
    dest: "{{ tomcat_tmp_storage }}"
    url: "{{ item }}/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/{{ tomcat_tar_archive }}"
    checksum: "{{ tomcat_version_specific[tomcat_version].checksum }}"

- name: Unarchive Tomcat
  when: not __tomcat_exists.stat.exists
  unarchive:
    remote_src: yes
    src: "{{ tomcat_tmp_storage }}/{{ tomcat_tar_archive }}"
    dest: "{{ tomcat_base_dir }}"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    keep_newer: yes
    # extra_opts: ['--strip-components=1', '--show-stored-names']

- name: Give Ownership Of Unarchived Folder
  file:
    state: directory
    path: "{{tomcat_base_dir }}/apache-tomcat-{{ tomcat_version }}"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"

- name: Create Symlink To Archive Location
  file:
    path: "{{ tomcat_instance_path }}"
    src: "{{ tomcat_base_dir }}/apache-tomcat-{{ tomcat_version }}"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    state: link

- name: Install standard server.xml
  when:
    - not tomcat_use_custom_server_xml
    - tomcat_configure_configs
  register: __tomcat_standard_server_xml
  template:
    src: server.xml.j2
    dest: "{{ tomcat_instance_path }}/conf/server.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install custom server.xml
  when:
    - tomcat_use_custom_server_xml
    - tomcat_configure_configs
  register: __tomcat_custom_server_xml
  template:
    src: "{{ tomcat_custom_server_xml }}"
    dest: "{{ tomcat_instance_path }}/conf/server.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install standard web.xml
  when:
    - not tomcat_use_custom_web_xml
    - tomcat_configure_configs
  register: __tomcat_standard_web_xml
  template:
    src: web.xml.j2
    dest: "{{ tomcat_instance_path }}/conf/web.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install custom web.xml
  when:
    - tomcat_use_custom_web_xml
    - tomcat_configure_configs
  register: __tomcat_custom_web_xml
  template:
    src: "{{ tomcat_custom_web_xml }}"
    dest: "{{ tomcat_instance_path }}/conf/web.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install standard context.xml
  when:
    - not tomcat_use_custom_context_xml
    - tomcat_configure_configs
  register: __tomcat_standard_context_xml
  template:
    src: context.xml.j2
    dest: "{{ tomcat_instance_path }}/conf/context.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install custom context.xml
  when:
    - tomcat_use_custom_context_xml
    - tomcat_configure_configs
  register: __tomcat_custom_context_xml
  template:
    src: "{{ tomcat_custom_context_xml }}"
    dest: "{{ tomcat_instance_path }}/conf/context.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install standard tomcat-users.xml
  when:
    - not tomcat_use_custom_tomcat_users_xml
    - tomcat_configure_configs
  register: __tomcat_standard_users_xml
  template:
    src: tomcat-users.xml.j2
    dest: "{{ tomcat_instance_path }}/conf/tomcat-users.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install custom tomcat-users.xml
  when: tomcat_use_custom_tomcat_users_xml
  register: __tomcat_custom_users_xml
  template:
    src: "{{ tomcat_custom_tomcat_users_xml }}"
    dest: "{{ tomcat_instance_path }}/conf/tomcat-users.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install Extra Libraries
  register: __tomcat_install_libs
  with_items: "{{ tomcat_extra_libs_path }}"
  when:
    - tomcat_configure_libs
  copy:
    src: "{{ item }}"
    dest: "{{ tomcat_instance_path }}/lib/"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install WebApps
  register: __tomcat_install_webapps
  with_items: "{{ tomcat_webapps_path }}"
  when:
    - tomcat_configure_webapps
  copy:
    src: "{{ item }}"
    dest: "{{ tomcat_instance_path }}/webapps/"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0755

- name: Check if systemd is present
  stat:
    path: "/sbin/init"
  register: __stat_init

- name: Install Tomcat Service with systemd
  include: service_systemd_tomcat.yml
  when: __stat_init.stat.islnk and ( __stat_init.stat.lnk_source is defined ) and ( "systemd" in __stat_init.stat.lnk_source )

- name: Install Tomcat Service with initctl
  include: service_ctl_tomcat.yml
  when: not __stat_init.stat.islnk