---
# tasks file for universal-tomcat

- name: Insure Required Packages Are Installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - tar
    - wget

- name: Include Variables For Specific Tomcat Version
  include_vars: "tomcat-{{ tomcat_version }}.yml"

- name: Create Temporary Storage Location
  file:
    state: directory
    path: "{{ tomcat_tmp_storage }}"

- name: Create Catalina Home
  file:
    state: directory
    path: "{{ tomcat_catalina_home }}"

- name: Download Tomcat
  get_url:
    dest: "{{ tomcat_tmp_storage }}"
    url: "{{ item }}/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/{{ tomcat_tar_archive }}"
    checksum: "{{ tomcat_checksum }}"
  ignore_errors: True
  with_items: "{{ tomcat_mirrors }}"

- name: Unarchive Tomcat
  unarchive:
    remote_src: yes
    src: "{{ tomcat_tmp_storage }}/{{ tomcat_tar_archive }}"
    dest: "{{ tomcat_catalina_home }}"
    keep_newer: yes
    extra_opts: ['--strip-components=1', '--show-stored-names']

- name: Check Unarchive Location
  command: "/usr/bin/env ls {{ tomcat_catalina_home }}"
  register: __tomcat_unarchive
  changed_when: False
  ignore_errors: True

- debug: var=__tomcat_unarchive
