---
# tasks file for universal-tomcat

- name: Insure Required Packages Are Installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - tar
    - wget

- name: Include Variables For Specific Tomcat Version
  include_vars: "tomcat-{{ tomcat_version }}.yml"

- name: Create Temporary Storage Location
  file:
    state: directory
    path: "{{ tomcat_tmp_storage }}"

- name: Create Catalina Home
  file:
    state: directory
    path: "{{ tomcat_catalina_home }}"

- name: Download Tomcat
  ignore_errors: True
  with_items: "{{ tomcat_mirrors }}"
  get_url:
    dest: "{{ tomcat_tmp_storage }}"
    url: "{{ item }}/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/{{ tomcat_tar_archive }}"
    checksum: "{{ tomcat_checksum }}"


- name: Unarchive Tomcat
  unarchive:
    remote_src: yes
    src: "{{ tomcat_tmp_storage }}/{{ tomcat_tar_archive }}"
    dest: "{{ tomcat_catalina_home }}"
    keep_newer: yes
    extra_opts: ['--strip-components=1', '--show-stored-names']

- name: Create Tomcat Group
  group:
    name: "{{ tomcat_user_group }}"
    state: present

- name: Create Tomcat user
  user:
    name: "{{ tomcat_user_name }}"
    home: "{{ tomcat_user_home }}"
    group: "{{ tomcat_user_group }}"
    system: "{{ tomcat_user_system }}"
    createhome: true
    comment: "Tomcat Service User"

- name: Create Instance Path Folders
  with_nested:
    - "{{ tomcat_instances }}"
    - "{{ tomcat_instance_directories }}"
  file:
    state: directory
    path: "{{ tomcat_instance_path }}/catalina/{{item.0.name}}/{{ item.1 }}"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0755

- name: Install server.xml
  with_items: "{{ tomcat_instances }}"
  template:
    src: server.xml.j2
    dest: "{{ tomcat_instance_path }}/catalina/{{ item.name }}/conf/server.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640

- name: Install web.xml
  with_items: "{{ tomcat_instances }}"
  template:
    src: web.xml.j2
    dest: "{{ tomcat_instance_path }}/catalina/{{ item.name }}/conf/web.xml"
    owner: "{{ tomcat_user_name }}"
    group: "{{ tomcat_user_group }}"
    mode: 0640
