---
# tasks file for universal-tomcat - start tomcat with startup.sh script

- name: Check if it's a docker container
  command: grep docker /proc/self/cgroup
  register: __is_docker_container
  ignore_errors: True

- name: Install Service
  when: __is_docker_container.stdout == ""
  register: __tomcat_service_ctl
  template:
    src: tomcat.conf.j2
    dest: /etc/init/tomcat.conf
    mode: 0644

- name: Reload Service
  when: __tomcat_service_ctl|changed
  service:
    name: tomcat
    state: reloaded

- name: Start Service
  when: __tomcat_service_ctl|changed
  service:
    name: tomcat
    state: started
    enabled: yes

- name: Start service tomcat with start-stop-daemon command
  command: start-stop-daemon --exec {{ tomcat_instance_path }}/bin/startup.sh --start
  when: __is_docker_container.stdout != ""